[package]
name = "handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { features = ["full"], version = "1"}
axum = "0.5.13"
serde = "1.0.140"
serde_json = "1.0.82"